// Curated N5 scope-and-sequence: which real words/kanji/grammar belong to each lesson.
// Readings and glosses here are ground truth facts, not AI-generated — pedagogical content
// (examples, common mistakes, memory tips, exercises) is generated per item on first visit,
// using this seed data as input, and cached (see N5 discrete-lesson-layer plan).

import type { GrammarPoint, KanjiEntry, VocabItem } from "./types.js";

export interface N5VocabSeed {
  japanese: string;
  reading: string;
  englishGloss: string;
}

export interface N5KanjiSeed {
  character: string;
  onReading: string;
  kunReading: string;
  englishGloss: string;
}

export interface N5GrammarSeed {
  pattern: string;
  englishGloss: string;
}

export interface N5LessonSpec {
  lessonNumber: number;
  isReview: boolean;
  theme: string;
  objectives: string[];
  vocab: N5VocabSeed[];
  kanji: N5KanjiSeed[];
  grammar: N5GrammarSeed[];
  reviewsLessons?: number[];
}

export const N5_LESSON_COUNT = 40;
export const N5_REVIEW_CADENCE = 5;

// ---- Fixed-item content generation DTOs ----
// Unlike GrammarDrillRequest/KanjiDrillRequest/ExtractRequest (which ask the AI to pick
// items freely), these request rich pedagogical content for specific seed items the
// syllabus already names, generated once per lesson and cached client-side.

export interface N5VocabContentRequest {
  sourceLanguage: string;
  targetLanguage: string;
  seeds: N5VocabSeed[];
}

export interface N5VocabContentResponse {
  items: VocabItem[]; // one per seed, same order
}

export interface N5KanjiContentRequest {
  sourceLanguage: string;
  seeds: N5KanjiSeed[];
}

export interface N5KanjiContentResponse {
  entries: KanjiEntry[]; // one per seed, same order
}

export interface N5GrammarContentRequest {
  sourceLanguage: string;
  targetLanguage: string;
  seeds: N5GrammarSeed[];
}

export interface N5GrammarContentResponse {
  points: GrammarPoint[]; // one per seed, same order
}

function review(lessonNumber: number): N5LessonSpec {
  return {
    lessonNumber,
    isReview: true,
    theme: "復習 (Review)",
    objectives: [
      "Review vocabulary, kanji, and grammar from the past four lessons",
      "No new material introduced",
    ],
    vocab: [],
    kanji: [],
    grammar: [],
    reviewsLessons: [lessonNumber - 4, lessonNumber - 3, lessonNumber - 2, lessonNumber - 1],
  };
}

export const N5_SYLLABUS: N5LessonSpec[] = [
  {
    lessonNumber: 1,
    isReview: false,
    theme: "「はじめまして」",
    objectives: [
      "Introduce yourself in Japanese",
      "Say your nationality and occupation",
      "Ask someone's name",
      "Read your first five kanji",
    ],
    vocab: [
      { japanese: "私", reading: "わたし", englishGloss: "I, me" },
      { japanese: "あなた", reading: "あなた", englishGloss: "you" },
      { japanese: "学生", reading: "がくせい", englishGloss: "student" },
      { japanese: "先生", reading: "せんせい", englishGloss: "teacher" },
      { japanese: "会社員", reading: "かいしゃいん", englishGloss: "office worker" },
      { japanese: "日本", reading: "にほん", englishGloss: "Japan" },
      { japanese: "台湾", reading: "たいわん", englishGloss: "Taiwan" },
      { japanese: "中国", reading: "ちゅうごく", englishGloss: "China" },
      { japanese: "人", reading: "ひと／じん", englishGloss: "person" },
      { japanese: "名前", reading: "なまえ", englishGloss: "name" },
      { japanese: "です", reading: "です", englishGloss: "to be" },
      { japanese: "はい", reading: "はい", englishGloss: "yes" },
      { japanese: "いいえ", reading: "いいえ", englishGloss: "no" },
      { japanese: "よろしく", reading: "よろしく", englishGloss: "please treat me well" },
      { japanese: "初めまして", reading: "はじめまして", englishGloss: "nice to meet you" },
      { japanese: "何", reading: "なに／なん", englishGloss: "what" },
      { japanese: "～さん", reading: "さん", englishGloss: "Mr./Ms." },
      { japanese: "～人", reading: "～じん", englishGloss: "nationality suffix" },
      { japanese: "友達", reading: "ともだち", englishGloss: "friend" },
      { japanese: "大学", reading: "だいがく", englishGloss: "university" },
    ],
    kanji: [
      { character: "人", onReading: "ジン、ニン", kunReading: "ひと", englishGloss: "person" },
      { character: "日", onReading: "ニチ、ジツ", kunReading: "ひ、か", englishGloss: "sun, day, Japan" },
      { character: "本", onReading: "ホン", kunReading: "もと", englishGloss: "book, origin, main" },
      { character: "学", onReading: "ガク", kunReading: "まな.ぶ", englishGloss: "study, learning" },
      { character: "生", onReading: "セイ、ショウ", kunReading: "い.きる、う.まれる、なま", englishGloss: "life, birth, raw" },
    ],
    grammar: [
      { pattern: "〜は〜です", englishGloss: "A is B" },
      { pattern: "〜ですか", englishGloss: "question marker: is it...?" },
    ],
  },
  {
    lessonNumber: 2,
    isReview: false,
    theme: "「数字とお金」",
    objectives: [
      "Count from 1 to 10,000",
      "Ask and state prices",
      "Talk about age using 歳",
    ],
    vocab: [
      { japanese: "一", reading: "いち", englishGloss: "one" },
      { japanese: "二", reading: "に", englishGloss: "two" },
      { japanese: "三", reading: "さん", englishGloss: "three" },
      { japanese: "四", reading: "よん", englishGloss: "four" },
      { japanese: "五", reading: "ご", englishGloss: "five" },
      { japanese: "六", reading: "ろく", englishGloss: "six" },
      { japanese: "七", reading: "なな", englishGloss: "seven" },
      { japanese: "八", reading: "はち", englishGloss: "eight" },
      { japanese: "九", reading: "きゅう", englishGloss: "nine" },
      { japanese: "十", reading: "じゅう", englishGloss: "ten" },
      { japanese: "百", reading: "ひゃく", englishGloss: "hundred" },
      { japanese: "千", reading: "せん", englishGloss: "thousand" },
      { japanese: "万", reading: "まん", englishGloss: "ten thousand" },
      { japanese: "円", reading: "えん", englishGloss: "yen" },
      { japanese: "歳", reading: "さい", englishGloss: "years old" },
      { japanese: "いくつ", reading: "いくつ", englishGloss: "how many" },
      { japanese: "いくら", reading: "いくら", englishGloss: "how much" },
      { japanese: "半分", reading: "はんぶん", englishGloss: "half" },
      { japanese: "全部", reading: "ぜんぶ", englishGloss: "all, everything" },
      { japanese: "同じ", reading: "おなじ", englishGloss: "same" },
      { japanese: "電話番号", reading: "でんわばんごう", englishGloss: "phone number" },
      { japanese: "お金", reading: "おかね", englishGloss: "money" },
      { japanese: "財布", reading: "さいふ", englishGloss: "wallet" },
      { japanese: "数える", reading: "かぞえる", englishGloss: "to count" },
      { japanese: "ちょうど", reading: "ちょうど", englishGloss: "exactly" },
    ],
    kanji: [
      { character: "一", onReading: "イチ、イツ", kunReading: "ひと.つ", englishGloss: "one" },
      { character: "二", onReading: "ニ", kunReading: "ふた.つ", englishGloss: "two" },
      { character: "三", onReading: "サン", kunReading: "みっ.つ", englishGloss: "three" },
    ],
    grammar: [
      { pattern: "〜も", englishGloss: "also, too" },
      { pattern: "〜の", englishGloss: "possessive/modifying particle: A の B" },
    ],
  },
  {
    lessonNumber: 3,
    isReview: false,
    theme: "「家族」",
    objectives: [
      "Name family members",
      "Use この／その／あの to point things out",
      "Talk about siblings and relatives",
    ],
    vocab: [
      { japanese: "家族", reading: "かぞく", englishGloss: "family" },
      { japanese: "父", reading: "ちち", englishGloss: "father (own)" },
      { japanese: "母", reading: "はは", englishGloss: "mother (own)" },
      { japanese: "兄", reading: "あに", englishGloss: "older brother (own)" },
      { japanese: "姉", reading: "あね", englishGloss: "older sister (own)" },
      { japanese: "弟", reading: "おとうと", englishGloss: "younger brother" },
      { japanese: "妹", reading: "いもうと", englishGloss: "younger sister" },
      { japanese: "両親", reading: "りょうしん", englishGloss: "parents" },
      { japanese: "子供", reading: "こども", englishGloss: "child" },
      { japanese: "赤ちゃん", reading: "あかちゃん", englishGloss: "baby" },
      { japanese: "おじいさん", reading: "おじいさん", englishGloss: "grandfather" },
      { japanese: "おばあさん", reading: "おばあさん", englishGloss: "grandmother" },
      { japanese: "おじさん", reading: "おじさん", englishGloss: "uncle" },
      { japanese: "おばさん", reading: "おばさん", englishGloss: "aunt" },
      { japanese: "兄弟", reading: "きょうだい", englishGloss: "siblings" },
      { japanese: "一人っ子", reading: "ひとりっこ", englishGloss: "only child" },
      { japanese: "結婚する", reading: "けっこんする", englishGloss: "to marry" },
      { japanese: "独身", reading: "どくしん", englishGloss: "single (unmarried)" },
      { japanese: "家庭", reading: "かてい", englishGloss: "household" },
      { japanese: "奥さん", reading: "おくさん", englishGloss: "wife (someone else's)" },
      { japanese: "ご主人", reading: "ごしゅじん", englishGloss: "husband (someone else's)" },
      { japanese: "年上", reading: "としうえ", englishGloss: "older (in age)" },
      { japanese: "年下", reading: "としした", englishGloss: "younger (in age)" },
      { japanese: "似ている", reading: "にている", englishGloss: "to resemble" },
      { japanese: "かわいい", reading: "かわいい", englishGloss: "cute" },
    ],
    kanji: [
      { character: "父", onReading: "フ", kunReading: "ちち", englishGloss: "father" },
      { character: "母", onReading: "ボ", kunReading: "はは", englishGloss: "mother" },
      { character: "子", onReading: "シ", kunReading: "こ", englishGloss: "child" },
    ],
    grammar: [
      { pattern: "これ・それ・あれ・どれ", englishGloss: "this/that/that over there/which one" },
      { pattern: "この・その・あの・どの＋Noun", englishGloss: "this/that/which + noun" },
    ],
  },
  {
    lessonNumber: 4,
    isReview: false,
    theme: "「今日は何日ですか」",
    objectives: [
      "Say today's date and day of the week",
      "Talk about this/next/last week, month, and year",
      "Say where things are with 〜があります",
    ],
    vocab: [
      { japanese: "今", reading: "いま", englishGloss: "now" },
      { japanese: "今日", reading: "きょう", englishGloss: "today" },
      { japanese: "明日", reading: "あした", englishGloss: "tomorrow" },
      { japanese: "昨日", reading: "きのう", englishGloss: "yesterday" },
      { japanese: "今週", reading: "こんしゅう", englishGloss: "this week" },
      { japanese: "来週", reading: "らいしゅう", englishGloss: "next week" },
      { japanese: "先週", reading: "せんしゅう", englishGloss: "last week" },
      { japanese: "今月", reading: "こんげつ", englishGloss: "this month" },
      { japanese: "来月", reading: "らいげつ", englishGloss: "next month" },
      { japanese: "先月", reading: "せんげつ", englishGloss: "last month" },
      { japanese: "今年", reading: "ことし", englishGloss: "this year" },
      { japanese: "来年", reading: "らいねん", englishGloss: "next year" },
      { japanese: "去年", reading: "きょねん", englishGloss: "last year" },
      { japanese: "月曜日", reading: "げつようび", englishGloss: "Monday" },
      { japanese: "火曜日", reading: "かようび", englishGloss: "Tuesday" },
      { japanese: "水曜日", reading: "すいようび", englishGloss: "Wednesday" },
      { japanese: "木曜日", reading: "もくようび", englishGloss: "Thursday" },
      { japanese: "金曜日", reading: "きんようび", englishGloss: "Friday" },
      { japanese: "土曜日", reading: "どようび", englishGloss: "Saturday" },
      { japanese: "日曜日", reading: "にちようび", englishGloss: "Sunday" },
      { japanese: "何曜日", reading: "なんようび", englishGloss: "what day of the week" },
      { japanese: "誕生日", reading: "たんじょうび", englishGloss: "birthday" },
      { japanese: "休み", reading: "やすみ", englishGloss: "day off, vacation" },
      { japanese: "予定", reading: "よてい", englishGloss: "schedule, plan" },
      { japanese: "時間", reading: "じかん", englishGloss: "time" },
    ],
    kanji: [
      { character: "今", onReading: "コン、キン", kunReading: "いま", englishGloss: "now" },
      { character: "月", onReading: "ゲツ、ガツ", kunReading: "つき", englishGloss: "month, moon" },
      { character: "年", onReading: "ネン", kunReading: "とし", englishGloss: "year" },
    ],
    grammar: [
      { pattern: "ここ・そこ・あそこ・どこ", englishGloss: "here/there/over there/where" },
      { pattern: "〜がいます", englishGloss: "there is/are (animate)" },
    ],
  },
  review(5),
  {
    lessonNumber: 6,
    isReview: false,
    theme: "「毎日の生活」",
    objectives: [
      "Describe your daily routine with polite verb forms",
      "Talk about things you have or places things exist",
    ],
    vocab: [
      { japanese: "起きる", reading: "おきる", englishGloss: "to wake up" },
      { japanese: "寝る", reading: "ねる", englishGloss: "to sleep" },
      { japanese: "行く", reading: "いく", englishGloss: "to go" },
      { japanese: "来る", reading: "くる", englishGloss: "to come" },
      { japanese: "帰る", reading: "かえる", englishGloss: "to return home" },
      { japanese: "食べる", reading: "たべる", englishGloss: "to eat" },
      { japanese: "飲む", reading: "のむ", englishGloss: "to drink" },
      { japanese: "見る", reading: "みる", englishGloss: "to see, watch" },
      { japanese: "聞く", reading: "きく", englishGloss: "to listen, ask" },
      { japanese: "読む", reading: "よむ", englishGloss: "to read" },
      { japanese: "書く", reading: "かく", englishGloss: "to write" },
      { japanese: "話す", reading: "はなす", englishGloss: "to speak" },
      { japanese: "買う", reading: "かう", englishGloss: "to buy" },
      { japanese: "する", reading: "する", englishGloss: "to do" },
      { japanese: "勉強する", reading: "べんきょうする", englishGloss: "to study" },
      { japanese: "働く", reading: "はたらく", englishGloss: "to work" },
      { japanese: "休む", reading: "やすむ", englishGloss: "to rest, take a day off" },
      { japanese: "会う", reading: "あう", englishGloss: "to meet" },
      { japanese: "住む", reading: "すむ", englishGloss: "to live, reside" },
      { japanese: "使う", reading: "つかう", englishGloss: "to use" },
      { japanese: "洗う", reading: "あらう", englishGloss: "to wash" },
      { japanese: "掃除する", reading: "そうじする", englishGloss: "to clean" },
      { japanese: "洗濯する", reading: "せんたくする", englishGloss: "to do laundry" },
      { japanese: "歯を磨く", reading: "はをみがく", englishGloss: "to brush teeth" },
      { japanese: "シャワーを浴びる", reading: "しゃわーをあびる", englishGloss: "to take a shower" },
    ],
    kanji: [
      { character: "食", onReading: "ショク", kunReading: "た.べる", englishGloss: "eat, food" },
      { character: "飲", onReading: "イン", kunReading: "の.む", englishGloss: "drink" },
      { character: "見", onReading: "ケン", kunReading: "み.る", englishGloss: "see, look" },
    ],
    grammar: [
      { pattern: "〜があります", englishGloss: "there is/are (inanimate)" },
      { pattern: "〜に〜があります／います", englishGloss: "location + existence" },
    ],
  },
  {
    lessonNumber: 7,
    isReview: false,
    theme: "「町の中で」",
    objectives: [
      "Name places around town",
      "Give simple directions",
      "Say what you like with 〜が好きです",
    ],
    vocab: [
      { japanese: "学校", reading: "がっこう", englishGloss: "school" },
      { japanese: "会社", reading: "かいしゃ", englishGloss: "company" },
      { japanese: "駅", reading: "えき", englishGloss: "station" },
      { japanese: "病院", reading: "びょういん", englishGloss: "hospital" },
      { japanese: "銀行", reading: "ぎんこう", englishGloss: "bank" },
      { japanese: "郵便局", reading: "ゆうびんきょく", englishGloss: "post office" },
      { japanese: "図書館", reading: "としょかん", englishGloss: "library" },
      { japanese: "公園", reading: "こうえん", englishGloss: "park" },
      { japanese: "デパート", reading: "でぱーと", englishGloss: "department store" },
      { japanese: "スーパー", reading: "すーぱー", englishGloss: "supermarket" },
      { japanese: "レストラン", reading: "れすとらん", englishGloss: "restaurant" },
      { japanese: "トイレ", reading: "といれ", englishGloss: "toilet, bathroom" },
      { japanese: "エレベーター", reading: "えれべーたー", englishGloss: "elevator" },
      { japanese: "道", reading: "みち", englishGloss: "road, way" },
      { japanese: "右", reading: "みぎ", englishGloss: "right" },
      { japanese: "左", reading: "ひだり", englishGloss: "left" },
      { japanese: "前", reading: "まえ", englishGloss: "front, before" },
      { japanese: "後ろ", reading: "うしろ", englishGloss: "behind" },
      { japanese: "中", reading: "なか", englishGloss: "inside" },
      { japanese: "外", reading: "そと", englishGloss: "outside" },
      { japanese: "建物", reading: "たてもの", englishGloss: "building" },
      { japanese: "町", reading: "まち", englishGloss: "town" },
      { japanese: "市", reading: "し", englishGloss: "city" },
      { japanese: "村", reading: "むら", englishGloss: "village" },
      { japanese: "場所", reading: "ばしょ", englishGloss: "place" },
    ],
    kanji: [
      { character: "校", onReading: "コウ", kunReading: "—", englishGloss: "school" },
      { character: "右", onReading: "ウ、ユウ", kunReading: "みぎ", englishGloss: "right" },
      { character: "左", onReading: "サ", kunReading: "ひだり", englishGloss: "left" },
    ],
    grammar: [
      { pattern: "数字＋つ／人／個（助数詞）", englishGloss: "counters" },
      { pattern: "〜は〜が好きです", englishGloss: "I like..." },
    ],
  },
  {
    lessonNumber: 8,
    isReview: false,
    theme: "「どんな人ですか」",
    objectives: [
      "Describe people and things with i-adjectives and na-adjectives",
      "Talk about the weather in past tense",
    ],
    vocab: [
      { japanese: "大きい", reading: "おおきい", englishGloss: "big" },
      { japanese: "小さい", reading: "ちいさい", englishGloss: "small" },
      { japanese: "新しい", reading: "あたらしい", englishGloss: "new" },
      { japanese: "古い", reading: "ふるい", englishGloss: "old (thing)" },
      { japanese: "いい", reading: "いい", englishGloss: "good" },
      { japanese: "悪い", reading: "わるい", englishGloss: "bad" },
      { japanese: "高い", reading: "たかい", englishGloss: "expensive, tall" },
      { japanese: "安い", reading: "やすい", englishGloss: "cheap" },
      { japanese: "暑い", reading: "あつい", englishGloss: "hot (weather)" },
      { japanese: "寒い", reading: "さむい", englishGloss: "cold (weather)" },
      { japanese: "忙しい", reading: "いそがしい", englishGloss: "busy" },
      { japanese: "暇な", reading: "ひまな", englishGloss: "free, not busy" },
      { japanese: "きれいな", reading: "きれいな", englishGloss: "pretty, clean" },
      { japanese: "静かな", reading: "しずかな", englishGloss: "quiet" },
      { japanese: "にぎやかな", reading: "にぎやかな", englishGloss: "lively" },
      { japanese: "有名な", reading: "ゆうめいな", englishGloss: "famous" },
      { japanese: "元気な", reading: "げんきな", englishGloss: "healthy, energetic" },
      { japanese: "好きな", reading: "すきな", englishGloss: "likable" },
      { japanese: "嫌いな", reading: "きらいな", englishGloss: "dislikable" },
      { japanese: "便利な", reading: "べんりな", englishGloss: "convenient" },
      { japanese: "不便な", reading: "ふべんな", englishGloss: "inconvenient" },
      { japanese: "楽しい", reading: "たのしい", englishGloss: "fun" },
      { japanese: "面白い", reading: "おもしろい", englishGloss: "interesting" },
      { japanese: "つまらない", reading: "つまらない", englishGloss: "boring" },
      { japanese: "難しい", reading: "むずかしい", englishGloss: "difficult" },
    ],
    kanji: [
      { character: "大", onReading: "ダイ、タイ", kunReading: "おお.きい", englishGloss: "big" },
      { character: "小", onReading: "ショウ", kunReading: "ちい.さい", englishGloss: "small" },
      { character: "新", onReading: "シン", kunReading: "あたら.しい", englishGloss: "new" },
    ],
    grammar: [
      { pattern: "動詞のます形（肯定・現在）", englishGloss: "polite present affirmative verbs" },
      { pattern: "動詞のません形（否定・現在）", englishGloss: "polite present negative verbs" },
    ],
  },
  {
    lessonNumber: 9,
    isReview: false,
    theme: "「晩ご飯は何ですか」",
    objectives: [
      "Order food and drink",
      "Talk about meals",
      "Use polite past-tense verbs",
    ],
    vocab: [
      { japanese: "ご飯", reading: "ごはん", englishGloss: "rice, meal" },
      { japanese: "パン", reading: "ぱん", englishGloss: "bread" },
      { japanese: "水", reading: "みず", englishGloss: "water" },
      { japanese: "お茶", reading: "おちゃ", englishGloss: "tea" },
      { japanese: "コーヒー", reading: "こーひー", englishGloss: "coffee" },
      { japanese: "肉", reading: "にく", englishGloss: "meat" },
      { japanese: "魚", reading: "さかな", englishGloss: "fish" },
      { japanese: "野菜", reading: "やさい", englishGloss: "vegetable" },
      { japanese: "果物", reading: "くだもの", englishGloss: "fruit" },
      { japanese: "卵", reading: "たまご", englishGloss: "egg" },
      { japanese: "牛乳", reading: "ぎゅうにゅう", englishGloss: "milk" },
      { japanese: "ジュース", reading: "じゅーす", englishGloss: "juice" },
      { japanese: "ビール", reading: "びーる", englishGloss: "beer" },
      { japanese: "朝ご飯", reading: "あさごはん", englishGloss: "breakfast" },
      { japanese: "昼ご飯", reading: "ひるごはん", englishGloss: "lunch" },
      { japanese: "晩ご飯", reading: "ばんごはん", englishGloss: "dinner" },
      { japanese: "お菓子", reading: "おかし", englishGloss: "snack, sweets" },
      { japanese: "塩", reading: "しお", englishGloss: "salt" },
      { japanese: "砂糖", reading: "さとう", englishGloss: "sugar" },
      { japanese: "醤油", reading: "しょうゆ", englishGloss: "soy sauce" },
      { japanese: "箸", reading: "はし", englishGloss: "chopsticks" },
      { japanese: "お腹が空く", reading: "おなかがすく", englishGloss: "to get hungry" },
      { japanese: "喉が渇く", reading: "のどがかわく", englishGloss: "to get thirsty" },
      { japanese: "美味しい", reading: "おいしい", englishGloss: "delicious" },
      { japanese: "まずい", reading: "まずい", englishGloss: "bad-tasting" },
    ],
    kanji: [
      { character: "肉", onReading: "ニク", kunReading: "—", englishGloss: "meat" },
      { character: "魚", onReading: "ギョ", kunReading: "さかな", englishGloss: "fish" },
      { character: "茶", onReading: "チャ、サ", kunReading: "—", englishGloss: "tea" },
    ],
    grammar: [
      { pattern: "動詞のました形（肯定・過去）", englishGloss: "polite past affirmative verbs" },
      { pattern: "動詞のませんでした形（否定・過去）", englishGloss: "polite past negative verbs" },
    ],
  },
  review(10),
  {
    lessonNumber: 11,
    isReview: false,
    theme: "「買い物」",
    objectives: [
      "Go shopping and ask for prices",
      "Talk about colors",
      "Use adjectives to compare items",
    ],
    vocab: [
      { japanese: "買い物", reading: "かいもの", englishGloss: "shopping" },
      { japanese: "店", reading: "みせ", englishGloss: "shop" },
      { japanese: "色", reading: "いろ", englishGloss: "color" },
      { japanese: "赤い", reading: "あかい", englishGloss: "red" },
      { japanese: "青い", reading: "あおい", englishGloss: "blue" },
      { japanese: "白い", reading: "しろい", englishGloss: "white" },
      { japanese: "黒い", reading: "くろい", englishGloss: "black" },
      { japanese: "黄色い", reading: "きいろい", englishGloss: "yellow" },
      { japanese: "クレジットカード", reading: "くれじっとかーど", englishGloss: "credit card" },
      { japanese: "レシート", reading: "れしーと", englishGloss: "receipt" },
      { japanese: "プレゼント", reading: "ぷれぜんと", englishGloss: "present" },
      { japanese: "セール", reading: "せーる", englishGloss: "sale" },
      { japanese: "店員", reading: "てんいん", englishGloss: "shop clerk" },
      { japanese: "お客さん", reading: "おきゃくさん", englishGloss: "customer" },
      { japanese: "サイズ", reading: "さいず", englishGloss: "size" },
      { japanese: "値段", reading: "ねだん", englishGloss: "price" },
      { japanese: "割引", reading: "わりびき", englishGloss: "discount" },
      { japanese: "試着する", reading: "しちゃくする", englishGloss: "to try on" },
      { japanese: "包む", reading: "つつむ", englishGloss: "to wrap" },
      { japanese: "袋", reading: "ふくろ", englishGloss: "bag" },
      { japanese: "欲しい", reading: "ほしい", englishGloss: "want (a thing)" },
      { japanese: "売る", reading: "うる", englishGloss: "to sell" },
      { japanese: "選ぶ", reading: "えらぶ", englishGloss: "to choose" },
      { japanese: "支払う", reading: "しはらう", englishGloss: "to pay" },
      { japanese: "現金", reading: "げんきん", englishGloss: "cash" },
    ],
    kanji: [
      { character: "買", onReading: "バイ", kunReading: "か.う", englishGloss: "buy" },
      { character: "店", onReading: "テン", kunReading: "みせ", englishGloss: "shop" },
      { character: "円", onReading: "エン", kunReading: "—", englishGloss: "yen, circle" },
    ],
    grammar: [
      { pattern: "〜を＋他動詞", englishGloss: "transitive verb + object marker を" },
      { pattern: "〜へ行きます／来ます／帰ります", englishGloss: "direction particle へ with motion verbs" },
    ],
  },
  {
    lessonNumber: 12,
    isReview: false,
    theme: "「体と健康」",
    objectives: [
      "Talk about body parts and symptoms",
      "Say what's hurting",
      "Compare two things",
    ],
    vocab: [
      { japanese: "頭", reading: "あたま", englishGloss: "head" },
      { japanese: "顔", reading: "かお", englishGloss: "face" },
      { japanese: "目", reading: "め", englishGloss: "eye" },
      { japanese: "耳", reading: "みみ", englishGloss: "ear" },
      { japanese: "鼻", reading: "はな", englishGloss: "nose" },
      { japanese: "口", reading: "くち", englishGloss: "mouth" },
      { japanese: "手", reading: "て", englishGloss: "hand" },
      { japanese: "足", reading: "あし", englishGloss: "leg, foot" },
      { japanese: "お腹", reading: "おなか", englishGloss: "stomach" },
      { japanese: "体", reading: "からだ", englishGloss: "body" },
      { japanese: "病気", reading: "びょうき", englishGloss: "sickness" },
      { japanese: "元気", reading: "げんき", englishGloss: "healthy, well" },
      { japanese: "薬", reading: "くすり", englishGloss: "medicine" },
      { japanese: "医者", reading: "いしゃ", englishGloss: "doctor" },
      { japanese: "看護師", reading: "かんごし", englishGloss: "nurse" },
      { japanese: "熱", reading: "ねつ", englishGloss: "fever" },
      { japanese: "痛い", reading: "いたい", englishGloss: "painful" },
      { japanese: "風邪", reading: "かぜ", englishGloss: "a cold (illness)" },
      { japanese: "怪我", reading: "けが", englishGloss: "injury" },
      { japanese: "咳", reading: "せき", englishGloss: "cough" },
      { japanese: "体重", reading: "たいじゅう", englishGloss: "body weight" },
      { japanese: "身長", reading: "しんちょう", englishGloss: "height" },
      { japanese: "健康", reading: "けんこう", englishGloss: "health" },
      { japanese: "入院する", reading: "にゅういんする", englishGloss: "to be hospitalized" },
      { japanese: "注射", reading: "ちゅうしゃ", englishGloss: "injection" },
    ],
    kanji: [
      { character: "体", onReading: "タイ", kunReading: "からだ", englishGloss: "body" },
      { character: "病", onReading: "ビョウ", kunReading: "やまい", englishGloss: "illness" },
      { character: "院", onReading: "イン", kunReading: "—", englishGloss: "institution" },
    ],
    grammar: [
      { pattern: "〜で（場所＋動作）", englishGloss: "location of an action, particle で" },
      { pattern: "〜で（手段・道具）", englishGloss: "means/instrument, particle で" },
    ],
  },
  {
    lessonNumber: 13,
    isReview: false,
    theme: "「今日の天気」",
    objectives: [
      "Talk about weather and seasons",
      "Say what you want using 〜がほしいです",
      "Use superlatives with 一番",
    ],
    vocab: [
      { japanese: "天気", reading: "てんき", englishGloss: "weather" },
      { japanese: "晴れ", reading: "はれ", englishGloss: "sunny" },
      { japanese: "雨", reading: "あめ", englishGloss: "rain" },
      { japanese: "雪", reading: "ゆき", englishGloss: "snow" },
      { japanese: "曇り", reading: "くもり", englishGloss: "cloudy" },
      { japanese: "風", reading: "かぜ", englishGloss: "wind" },
      { japanese: "台風", reading: "たいふう", englishGloss: "typhoon" },
      { japanese: "春", reading: "はる", englishGloss: "spring" },
      { japanese: "夏", reading: "なつ", englishGloss: "summer" },
      { japanese: "秋", reading: "あき", englishGloss: "autumn" },
      { japanese: "冬", reading: "ふゆ", englishGloss: "winter" },
      { japanese: "涼しい", reading: "すずしい", englishGloss: "cool (weather)" },
      { japanese: "暖かい", reading: "あたたかい", englishGloss: "warm (weather)" },
      { japanese: "気温", reading: "きおん", englishGloss: "temperature" },
      { japanese: "予報", reading: "よほう", englishGloss: "forecast" },
      { japanese: "傘", reading: "かさ", englishGloss: "umbrella" },
      { japanese: "濡れる", reading: "ぬれる", englishGloss: "to get wet" },
      { japanese: "晴れる", reading: "はれる", englishGloss: "to clear up" },
      { japanese: "降る", reading: "ふる", englishGloss: "to fall (rain/snow)" },
      { japanese: "吹く", reading: "ふく", englishGloss: "to blow (wind)" },
      { japanese: "虹", reading: "にじ", englishGloss: "rainbow" },
      { japanese: "雷", reading: "かみなり", englishGloss: "thunder" },
      { japanese: "湿度", reading: "しつど", englishGloss: "humidity" },
      { japanese: "四季", reading: "しき", englishGloss: "four seasons" },
      { japanese: "気候", reading: "きこう", englishGloss: "climate" },
    ],
    kanji: [
      { character: "天", onReading: "テン", kunReading: "あめ", englishGloss: "heaven, sky" },
      { character: "気", onReading: "キ、ケ", kunReading: "—", englishGloss: "spirit, air" },
      { character: "雨", onReading: "ウ", kunReading: "あめ", englishGloss: "rain" },
    ],
    grammar: [
      { pattern: "い形容詞＋です", englishGloss: "i-adjective + です" },
      { pattern: "い形容詞の否定形（〜くないです）", englishGloss: "i-adjective negative form" },
    ],
  },
  {
    lessonNumber: 14,
    isReview: false,
    theme: "「趣味は何ですか」",
    objectives: [
      "Talk about hobbies",
      "Say what you want to do with 〜たいです",
      "Make suggestions with 〜ましょう",
    ],
    vocab: [
      { japanese: "趣味", reading: "しゅみ", englishGloss: "hobby" },
      { japanese: "音楽", reading: "おんがく", englishGloss: "music" },
      { japanese: "映画", reading: "えいが", englishGloss: "movie" },
      { japanese: "スポーツ", reading: "すぽーつ", englishGloss: "sports" },
      { japanese: "本", reading: "ほん", englishGloss: "book" },
      { japanese: "テレビ", reading: "てれび", englishGloss: "TV" },
      { japanese: "ゲーム", reading: "げーむ", englishGloss: "game" },
      { japanese: "写真", reading: "しゃしん", englishGloss: "photo" },
      { japanese: "絵", reading: "え", englishGloss: "picture, drawing" },
      { japanese: "歌", reading: "うた", englishGloss: "song" },
      { japanese: "ダンス", reading: "だんす", englishGloss: "dance" },
      { japanese: "泳ぐ", reading: "およぐ", englishGloss: "to swim" },
      { japanese: "走る", reading: "はしる", englishGloss: "to run" },
      { japanese: "遊ぶ", reading: "あそぶ", englishGloss: "to play" },
      { japanese: "踊る", reading: "おどる", englishGloss: "to dance" },
      { japanese: "歌う", reading: "うたう", englishGloss: "to sing" },
      { japanese: "描く", reading: "かく", englishGloss: "to draw" },
      { japanese: "楽器", reading: "がっき", englishGloss: "musical instrument" },
      { japanese: "ピアノ", reading: "ぴあの", englishGloss: "piano" },
      { japanese: "ギター", reading: "ぎたー", englishGloss: "guitar" },
      { japanese: "得意な", reading: "とくいな", englishGloss: "good at" },
      { japanese: "苦手な", reading: "にがてな", englishGloss: "poor at" },
      { japanese: "休日", reading: "きゅうじつ", englishGloss: "day off" },
      { japanese: "楽しむ", reading: "たのしむ", englishGloss: "to enjoy" },
      { japanese: "集める", reading: "あつめる", englishGloss: "to collect" },
    ],
    kanji: [
      { character: "音", onReading: "オン、イン", kunReading: "おと", englishGloss: "sound" },
      { character: "楽", onReading: "ガク、ラク", kunReading: "たの.しい", englishGloss: "music, fun" },
      { character: "歌", onReading: "カ", kunReading: "うた", englishGloss: "song" },
    ],
    grammar: [
      { pattern: "な形容詞＋です", englishGloss: "na-adjective + です" },
      { pattern: "な形容詞の否定形（〜じゃないです）", englishGloss: "na-adjective negative form" },
    ],
  },
  review(15),
  {
    lessonNumber: 16,
    isReview: false,
    theme: "「学校と仕事」",
    objectives: [
      "Talk about school and work life",
      "Invite someone with 〜ませんか",
      "Use the te-form of verbs",
    ],
    vocab: [
      { japanese: "授業", reading: "じゅぎょう", englishGloss: "class, lesson" },
      { japanese: "宿題", reading: "しゅくだい", englishGloss: "homework" },
      { japanese: "試験", reading: "しけん", englishGloss: "exam" },
      { japanese: "教室", reading: "きょうしつ", englishGloss: "classroom" },
      { japanese: "会議", reading: "かいぎ", englishGloss: "meeting" },
      { japanese: "用事", reading: "ようじ", englishGloss: "errand, business" },
      { japanese: "週末", reading: "しゅうまつ", englishGloss: "weekend" },
      { japanese: "始まる", reading: "はじまる", englishGloss: "to begin" },
      { japanese: "終わる", reading: "おわる", englishGloss: "to end" },
      { japanese: "簡単な", reading: "かんたんな", englishGloss: "simple" },
      { japanese: "頑張る", reading: "がんばる", englishGloss: "to do one's best" },
      { japanese: "塾", reading: "じゅく", englishGloss: "cram school" },
      { japanese: "留学", reading: "りゅうがく", englishGloss: "studying abroad" },
      { japanese: "卒業する", reading: "そつぎょうする", englishGloss: "to graduate" },
      { japanese: "入学する", reading: "にゅうがくする", englishGloss: "to enter school" },
      { japanese: "成績", reading: "せいせき", englishGloss: "grades" },
      { japanese: "点数", reading: "てんすう", englishGloss: "score, points" },
      { japanese: "合格する", reading: "ごうかくする", englishGloss: "to pass (an exam)" },
      { japanese: "失敗する", reading: "しっぱいする", englishGloss: "to fail" },
      { japanese: "提出する", reading: "ていしゅつする", englishGloss: "to submit" },
      { japanese: "質問する", reading: "しつもんする", englishGloss: "to ask a question" },
      { japanese: "答える", reading: "こたえる", englishGloss: "to answer" },
      { japanese: "説明する", reading: "せつめいする", englishGloss: "to explain" },
      { japanese: "予習する", reading: "よしゅうする", englishGloss: "to prepare for class" },
      { japanese: "復習する", reading: "ふくしゅうする", englishGloss: "to review" },
    ],
    kanji: [
      { character: "会", onReading: "カイ", kunReading: "あ.う", englishGloss: "meet, meeting" },
      { character: "社", onReading: "シャ", kunReading: "やしろ", englishGloss: "company, shrine" },
      { character: "員", onReading: "イン", kunReading: "—", englishGloss: "member, staff" },
    ],
    grammar: [
      { pattern: "形容詞＋名詞", englishGloss: "adjective modifying a noun" },
      { pattern: "〜くて／〜で（形容詞の接続）", englishGloss: "connecting adjectives (te-form of adjectives)" },
    ],
  },
  {
    lessonNumber: 17,
    isReview: false,
    theme: "「駅までどう行きますか」",
    objectives: [
      "Talk about transportation",
      "Ask for and give directions",
      "Compare travel options",
    ],
    vocab: [
      { japanese: "電車", reading: "でんしゃ", englishGloss: "train" },
      { japanese: "バス", reading: "ばす", englishGloss: "bus" },
      { japanese: "タクシー", reading: "たくしー", englishGloss: "taxi" },
      { japanese: "飛行機", reading: "ひこうき", englishGloss: "airplane" },
      { japanese: "車", reading: "くるま", englishGloss: "car" },
      { japanese: "自転車", reading: "じてんしゃ", englishGloss: "bicycle" },
      { japanese: "空港", reading: "くうこう", englishGloss: "airport" },
      { japanese: "切符", reading: "きっぷ", englishGloss: "ticket" },
      { japanese: "乗る", reading: "のる", englishGloss: "to ride" },
      { japanese: "降りる", reading: "おりる", englishGloss: "to get off" },
      { japanese: "歩く", reading: "あるく", englishGloss: "to walk" },
      { japanese: "運転する", reading: "うんてんする", englishGloss: "to drive" },
      { japanese: "速い", reading: "はやい", englishGloss: "fast" },
      { japanese: "遅い", reading: "おそい", englishGloss: "slow" },
      { japanese: "事故", reading: "じこ", englishGloss: "accident" },
      { japanese: "渋滞", reading: "じゅうたい", englishGloss: "traffic jam" },
      { japanese: "時刻表", reading: "じこくひょう", englishGloss: "timetable" },
      { japanese: "乗り換える", reading: "のりかえる", englishGloss: "to transfer" },
      { japanese: "定期券", reading: "ていきけん", englishGloss: "commuter pass" },
      { japanese: "運賃", reading: "うんちん", englishGloss: "fare" },
      { japanese: "混んでいる", reading: "こんでいる", englishGloss: "crowded" },
      { japanese: "空いている", reading: "すいている", englishGloss: "empty, not crowded" },
      { japanese: "到着する", reading: "とうちゃくする", englishGloss: "to arrive" },
      { japanese: "出発する", reading: "しゅっぱつする", englishGloss: "to depart" },
      { japanese: "地図", reading: "ちず", englishGloss: "map" },
    ],
    kanji: [
      { character: "電", onReading: "デン", kunReading: "—", englishGloss: "electricity" },
      { character: "車", onReading: "シャ", kunReading: "くるま", englishGloss: "car, vehicle" },
      { character: "道", onReading: "ドウ", kunReading: "みち", englishGloss: "road, way" },
    ],
    grammar: [
      { pattern: "〜と〜と、どちらが〜ですか", englishGloss: "which is more...? (comparison)" },
      { pattern: "〜より〜のほうが〜です", englishGloss: "X is more ... than Y" },
    ],
  },
  {
    lessonNumber: 18,
    isReview: false,
    theme: "「私の部屋」",
    objectives: [
      "Describe your room and home",
      "Ask and give permission with 〜てもいいですか",
      "State prohibitions with 〜てはいけません",
    ],
    vocab: [
      { japanese: "家", reading: "いえ", englishGloss: "house" },
      { japanese: "部屋", reading: "へや", englishGloss: "room" },
      { japanese: "台所", reading: "だいどころ", englishGloss: "kitchen" },
      { japanese: "お風呂", reading: "おふろ", englishGloss: "bath" },
      { japanese: "玄関", reading: "げんかん", englishGloss: "entrance" },
      { japanese: "ベッド", reading: "べっど", englishGloss: "bed" },
      { japanese: "机", reading: "つくえ", englishGloss: "desk" },
      { japanese: "椅子", reading: "いす", englishGloss: "chair" },
      { japanese: "テーブル", reading: "てーぶる", englishGloss: "table" },
      { japanese: "窓", reading: "まど", englishGloss: "window" },
      { japanese: "ドア", reading: "どあ", englishGloss: "door" },
      { japanese: "棚", reading: "たな", englishGloss: "shelf" },
      { japanese: "冷蔵庫", reading: "れいぞうこ", englishGloss: "refrigerator" },
      { japanese: "エアコン", reading: "えあこん", englishGloss: "air conditioner" },
      { japanese: "電気", reading: "でんき", englishGloss: "electricity, light" },
      { japanese: "引っ越す", reading: "ひっこす", englishGloss: "to move (residence)" },
      { japanese: "住所", reading: "じゅうしょ", englishGloss: "address" },
      { japanese: "アパート", reading: "あぱーと", englishGloss: "apartment" },
      { japanese: "マンション", reading: "まんしょん", englishGloss: "condominium" },
      { japanese: "広い", reading: "ひろい", englishGloss: "spacious" },
      { japanese: "狭い", reading: "せまい", englishGloss: "cramped, narrow" },
      { japanese: "庭", reading: "にわ", englishGloss: "garden, yard" },
      { japanese: "鍵", reading: "かぎ", englishGloss: "key" },
      { japanese: "洗濯機", reading: "せんたくき", englishGloss: "washing machine" },
      { japanese: "布団", reading: "ふとん", englishGloss: "futon" },
    ],
    kanji: [
      { character: "家", onReading: "カ、ケ", kunReading: "いえ、や", englishGloss: "house, home" },
      { character: "部", onReading: "ブ", kunReading: "—", englishGloss: "part, section" },
      { character: "屋", onReading: "オク", kunReading: "や", englishGloss: "shop, roof" },
    ],
    grammar: [
      { pattern: "〜の中で〜が一番〜です", englishGloss: "of all X, Y is the most..." },
      { pattern: "〜がほしいです", englishGloss: "I want (a thing)" },
    ],
  },
  {
    lessonNumber: 19,
    isReview: false,
    theme: "「電話とメール」",
    objectives: [
      "Talk about phones, email, and technology",
      "Say what you want to do with 〜たいです",
      "Make suggestions with 〜ましょう",
    ],
    vocab: [
      { japanese: "電話", reading: "でんわ", englishGloss: "telephone" },
      { japanese: "携帯", reading: "けーたい", englishGloss: "cell phone" },
      { japanese: "スマホ", reading: "すまほ", englishGloss: "smartphone" },
      { japanese: "メール", reading: "めーる", englishGloss: "email" },
      { japanese: "手紙", reading: "てがみ", englishGloss: "letter" },
      { japanese: "インターネット", reading: "いんたーねっと", englishGloss: "internet" },
      { japanese: "パソコン", reading: "ぱそこん", englishGloss: "computer" },
      { japanese: "アプリ", reading: "あぷり", englishGloss: "app" },
      { japanese: "送る", reading: "おくる", englishGloss: "to send" },
      { japanese: "かける", reading: "かける", englishGloss: "to make a call" },
      { japanese: "もらう", reading: "もらう", englishGloss: "to receive" },
      { japanese: "あげる", reading: "あげる", englishGloss: "to give" },
      { japanese: "くれる", reading: "くれる", englishGloss: "to give (to me)" },
      { japanese: "連絡する", reading: "れんらくする", englishGloss: "to contact" },
      { japanese: "検索する", reading: "けんさくする", englishGloss: "to search" },
      { japanese: "撮る", reading: "とる", englishGloss: "to take (a photo)" },
      { japanese: "壊れる", reading: "こわれる", englishGloss: "to break" },
      { japanese: "充電する", reading: "じゅうでんする", englishGloss: "to charge (a battery)" },
      { japanese: "繋がる", reading: "つながる", englishGloss: "to connect" },
      { japanese: "画面", reading: "がめん", englishGloss: "screen" },
      { japanese: "ボタン", reading: "ぼたん", englishGloss: "button" },
      { japanese: "文字", reading: "もじ", englishGloss: "character, text" },
      { japanese: "届く", reading: "とどく", englishGloss: "to arrive, be delivered" },
      { japanese: "動画", reading: "どうが", englishGloss: "video" },
      { japanese: "更新する", reading: "こうしんする", englishGloss: "to update" },
    ],
    kanji: [
      { character: "話", onReading: "ワ", kunReading: "はな.す", englishGloss: "talk, speak" },
      { character: "書", onReading: "ショ", kunReading: "か.く", englishGloss: "write" },
      { character: "読", onReading: "ドク", kunReading: "よ.む", englishGloss: "read" },
    ],
    grammar: [
      { pattern: "動詞のたい形", englishGloss: "want to do (verb たい form)" },
      { pattern: "〜ましょう", englishGloss: "let's do..." },
    ],
  },
  review(20),
  {
    lessonNumber: 21,
    isReview: false,
    theme: "「一日のスケジュール」",
    objectives: [
      "Describe your daily schedule",
      "Sequence actions before/after another",
      "Use the te-form for connected actions",
    ],
    vocab: [
      { japanese: "朝", reading: "あさ", englishGloss: "morning" },
      { japanese: "昼", reading: "ひる", englishGloss: "noon, daytime" },
      { japanese: "夜", reading: "よる", englishGloss: "night" },
      { japanese: "夕方", reading: "ゆうがた", englishGloss: "evening" },
      { japanese: "午前", reading: "ごぜん", englishGloss: "a.m." },
      { japanese: "午後", reading: "ごご", englishGloss: "p.m." },
      { japanese: "毎日", reading: "まいにち", englishGloss: "every day" },
      { japanese: "毎朝", reading: "まいあさ", englishGloss: "every morning" },
      { japanese: "毎晩", reading: "まいばん", englishGloss: "every night" },
      { japanese: "時々", reading: "ときどき", englishGloss: "sometimes" },
      { japanese: "いつも", reading: "いつも", englishGloss: "always" },
      { japanese: "たまに", reading: "たまに", englishGloss: "occasionally" },
      { japanese: "約束", reading: "やくそく", englishGloss: "promise, appointment" },
      { japanese: "遅刻する", reading: "ちこくする", englishGloss: "to be late" },
      { japanese: "間に合う", reading: "まにあう", englishGloss: "to make it in time" },
      { japanese: "早く", reading: "はやく", englishGloss: "early" },
      { japanese: "遅く", reading: "おそく", englishGloss: "late" },
      { japanese: "もうすぐ", reading: "もうすぐ", englishGloss: "soon" },
      { japanese: "さっき", reading: "さっき", englishGloss: "a moment ago" },
      { japanese: "これから", reading: "これから", englishGloss: "from now on" },
      { japanese: "ずっと", reading: "ずっと", englishGloss: "the whole time" },
      { japanese: "しばらく", reading: "しばらく", englishGloss: "for a while" },
      { japanese: "久しぶり", reading: "ひさしぶり", englishGloss: "long time no see" },
      { japanese: "最近", reading: "さいきん", englishGloss: "recently" },
      { japanese: "そろそろ", reading: "そろそろ", englishGloss: "soon, about time to" },
    ],
    kanji: [
      { character: "週", onReading: "シュウ", kunReading: "—", englishGloss: "week" },
      { character: "朝", onReading: "チョウ", kunReading: "あさ", englishGloss: "morning" },
      { character: "夜", onReading: "ヤ", kunReading: "よる", englishGloss: "night" },
    ],
    grammar: [
      { pattern: "〜ましょうか", englishGloss: "shall I/we...?" },
      { pattern: "〜ませんか", englishGloss: "won't you...? (invitation)" },
      { pattern: "動詞のて形", englishGloss: "te-form of verbs" },
    ],
  },
  {
    lessonNumber: 22,
    isReview: false,
    theme: "「貸してください」",
    objectives: [
      "Ask to borrow and lend things",
      "List example actions with 〜たり〜たりします",
      "Use giving/receiving verbs correctly",
    ],
    vocab: [
      { japanese: "貸す", reading: "かす", englishGloss: "to lend" },
      { japanese: "借りる", reading: "かりる", englishGloss: "to borrow" },
      { japanese: "返す", reading: "かえす", englishGloss: "to give back" },
      { japanese: "手伝う", reading: "てつだう", englishGloss: "to help" },
      { japanese: "教える", reading: "おしえる", englishGloss: "to teach" },
      { japanese: "習う", reading: "ならう", englishGloss: "to learn" },
      { japanese: "頼む", reading: "たのむ", englishGloss: "to request" },
      { japanese: "お願いする", reading: "おねがいする", englishGloss: "to ask a favor" },
      { japanese: "どうぞ", reading: "どうぞ", englishGloss: "please, go ahead" },
      { japanese: "どうも", reading: "どうも", englishGloss: "thanks, somewhat" },
      { japanese: "ください", reading: "ください", englishGloss: "please give me" },
      { japanese: "見せる", reading: "みせる", englishGloss: "to show" },
      { japanese: "持つ", reading: "もつ", englishGloss: "to hold, have" },
      { japanese: "持ってくる", reading: "もってくる", englishGloss: "to bring" },
      { japanese: "思い出す", reading: "おもいだす", englishGloss: "to recall" },
      { japanese: "決める", reading: "きめる", englishGloss: "to decide" },
      { japanese: "落とす", reading: "おとす", englishGloss: "to drop" },
      { japanese: "渡す", reading: "わたす", englishGloss: "to hand over" },
      { japanese: "交換する", reading: "こうかんする", englishGloss: "to exchange" },
      { japanese: "頼る", reading: "たよる", englishGloss: "to rely on" },
      { japanese: "助ける", reading: "たすける", englishGloss: "to help, rescue" },
      { japanese: "受け取る", reading: "うけとる", englishGloss: "to receive" },
      { japanese: "配る", reading: "くばる", englishGloss: "to distribute" },
      { japanese: "分ける", reading: "わける", englishGloss: "to divide, share" },
      { japanese: "許す", reading: "ゆるす", englishGloss: "to forgive, allow" },
    ],
    kanji: [
      { character: "教", onReading: "キョウ", kunReading: "おし.える", englishGloss: "teach" },
      { character: "習", onReading: "シュウ", kunReading: "なら.う", englishGloss: "learn, practice" },
      { character: "持", onReading: "ジ", kunReading: "も.つ", englishGloss: "hold, have" },
    ],
    grammar: [
      { pattern: "〜てください", englishGloss: "please do" },
      { pattern: "〜ています（進行）", englishGloss: "-ing, ongoing action" },
      { pattern: "〜ています（状態）", englishGloss: "resulting state" },
    ],
  },
  {
    lessonNumber: 23,
    isReview: false,
    theme: "「どう思いますか」",
    objectives: [
      "Share opinions and feelings",
      "State guesses with 〜と思います／〜でしょう",
      "Describe appearances with 〜そうです",
    ],
    vocab: [
      { japanese: "嬉しい", reading: "うれしい", englishGloss: "happy" },
      { japanese: "悲しい", reading: "かなしい", englishGloss: "sad" },
      { japanese: "寂しい", reading: "さびしい", englishGloss: "lonely" },
      { japanese: "恥ずかしい", reading: "はずかしい", englishGloss: "embarrassed" },
      { japanese: "怖い", reading: "こわい", englishGloss: "scary" },
      { japanese: "心配な", reading: "しんぱいな", englishGloss: "worried" },
      { japanese: "大丈夫", reading: "だいじょうぶ", englishGloss: "alright, okay" },
      { japanese: "安心する", reading: "あんしんする", englishGloss: "to feel relieved" },
      { japanese: "怒る", reading: "おこる", englishGloss: "to get angry" },
      { japanese: "思う", reading: "おもう", englishGloss: "to think" },
      { japanese: "分かる", reading: "わかる", englishGloss: "to understand" },
      { japanese: "知る", reading: "しる", englishGloss: "to know" },
      { japanese: "忘れる", reading: "わすれる", englishGloss: "to forget" },
      { japanese: "覚える", reading: "おぼえる", englishGloss: "to memorize" },
      { japanese: "意見", reading: "いけん", englishGloss: "opinion" },
      { japanese: "理由", reading: "りゆう", englishGloss: "reason" },
      { japanese: "大切な", reading: "たいせつな", englishGloss: "important" },
      { japanese: "必要な", reading: "ひつような", englishGloss: "necessary" },
      { japanese: "泣く", reading: "なく", englishGloss: "to cry" },
      { japanese: "笑う", reading: "わらう", englishGloss: "to laugh" },
      { japanese: "驚く", reading: "おどろく", englishGloss: "to be surprised" },
      { japanese: "緊張する", reading: "きんちょうする", englishGloss: "to be nervous" },
      { japanese: "感じる", reading: "かんじる", englishGloss: "to feel" },
      { japanese: "楽", reading: "らく", englishGloss: "comfortable, easy" },
      { japanese: "気持ち", reading: "きもち", englishGloss: "feeling" },
    ],
    kanji: [
      { character: "思", onReading: "シ", kunReading: "おも.う", englishGloss: "think" },
      { character: "知", onReading: "チ", kunReading: "し.る", englishGloss: "know" },
      { character: "忘", onReading: "ボウ", kunReading: "わす.れる", englishGloss: "forget" },
    ],
    grammar: [
      { pattern: "〜てもいいですか", englishGloss: "may I...?" },
      { pattern: "〜てはいけません", englishGloss: "must not do" },
      { pattern: "〜から〜まで", englishGloss: "from...to..." },
    ],
  },
  {
    lessonNumber: 24,
    isReview: false,
    theme: "「自然と動物」",
    objectives: [
      "Talk about nature and animals",
      "Give reasons with 〜から／〜ので",
      "Talk about the timing of events with 〜とき",
    ],
    vocab: [
      { japanese: "山", reading: "やま", englishGloss: "mountain" },
      { japanese: "川", reading: "かわ", englishGloss: "river" },
      { japanese: "海", reading: "うみ", englishGloss: "sea" },
      { japanese: "空", reading: "そら", englishGloss: "sky" },
      { japanese: "星", reading: "ほし", englishGloss: "star" },
      { japanese: "月", reading: "つき", englishGloss: "moon" },
      { japanese: "太陽", reading: "たいよう", englishGloss: "sun" },
      { japanese: "花", reading: "はな", englishGloss: "flower" },
      { japanese: "木", reading: "き", englishGloss: "tree" },
      { japanese: "犬", reading: "いぬ", englishGloss: "dog" },
      { japanese: "猫", reading: "ねこ", englishGloss: "cat" },
      { japanese: "鳥", reading: "とり", englishGloss: "bird" },
      { japanese: "魚", reading: "さかな", englishGloss: "fish (animal)" },
      { japanese: "動物", reading: "どうぶつ", englishGloss: "animal" },
      { japanese: "自然", reading: "しぜん", englishGloss: "nature" },
      { japanese: "森", reading: "もり", englishGloss: "forest" },
      { japanese: "散歩する", reading: "さんぽする", englishGloss: "to take a walk" },
      { japanese: "咲く", reading: "さく", englishGloss: "to bloom" },
      { japanese: "飛ぶ", reading: "とぶ", englishGloss: "to fly" },
      { japanese: "鳴く", reading: "なく", englishGloss: "to chirp, cry (animal)" },
      { japanese: "虫", reading: "むし", englishGloss: "insect" },
      { japanese: "石", reading: "いし", englishGloss: "stone" },
      { japanese: "土", reading: "つち", englishGloss: "soil" },
      { japanese: "草", reading: "くさ", englishGloss: "grass" },
      { japanese: "湖", reading: "みずうみ", englishGloss: "lake" },
    ],
    kanji: [
      { character: "山", onReading: "サン", kunReading: "やま", englishGloss: "mountain" },
      { character: "川", onReading: "セン", kunReading: "かわ", englishGloss: "river" },
      { character: "花", onReading: "カ", kunReading: "はな", englishGloss: "flower" },
    ],
    grammar: [
      { pattern: "〜ので", englishGloss: "because (softer)" },
      { pattern: "〜から（理由）", englishGloss: "because (direct reason)" },
      { pattern: "〜とき", englishGloss: "when..." },
    ],
  },
  review(25),
  {
    lessonNumber: 26,
    isReview: false,
    theme: "「旅行に行きます」",
    objectives: [
      "Talk about travel plans",
      "Express obligation with 〜なければなりません",
      "Say what's not required with 〜なくてもいいです",
    ],
    vocab: [
      { japanese: "旅行", reading: "りょこう", englishGloss: "travel" },
      { japanese: "ホテル", reading: "ほてる", englishGloss: "hotel" },
      { japanese: "観光地", reading: "かんこうち", englishGloss: "tourist spot" },
      { japanese: "パスポート", reading: "ぱすぽーと", englishGloss: "passport" },
      { japanese: "予約する", reading: "よやくする", englishGloss: "to make a reservation" },
      { japanese: "観光する", reading: "かんこうする", englishGloss: "to sightsee" },
      { japanese: "お土産", reading: "おみやげ", englishGloss: "souvenir" },
      { japanese: "泊まる", reading: "とまる", englishGloss: "to stay overnight" },
      { japanese: "案内する", reading: "あんないする", englishGloss: "to guide" },
      { japanese: "荷物", reading: "にもつ", englishGloss: "luggage" },
      { japanese: "外国", reading: "がいこく", englishGloss: "foreign country" },
      { japanese: "国", reading: "くに", englishGloss: "country" },
      { japanese: "文化", reading: "ぶんか", englishGloss: "culture" },
      { japanese: "習慣", reading: "しゅうかん", englishGloss: "custom" },
      { japanese: "言葉", reading: "ことば", englishGloss: "language, word" },
      { japanese: "漢字", reading: "かんじ", englishGloss: "kanji" },
      { japanese: "英語", reading: "えいご", englishGloss: "English" },
      { japanese: "日本語", reading: "にほんご", englishGloss: "Japanese language" },
      { japanese: "両替する", reading: "りょうがえする", englishGloss: "to exchange currency" },
      { japanese: "免税店", reading: "めんぜいてん", englishGloss: "duty-free shop" },
      { japanese: "ツアー", reading: "つあー", englishGloss: "tour" },
      { japanese: "一人旅", reading: "ひとりたび", englishGloss: "solo trip" },
      { japanese: "海外", reading: "かいがい", englishGloss: "overseas" },
      { japanese: "記念", reading: "きねん", englishGloss: "commemoration, memento" },
      { japanese: "旅館", reading: "りょかん", englishGloss: "traditional inn" },
    ],
    kanji: [
      { character: "旅", onReading: "リョ", kunReading: "たび", englishGloss: "travel, trip" },
      { character: "行", onReading: "コウ、ギョウ", kunReading: "い.く", englishGloss: "go" },
      { character: "外", onReading: "ガイ", kunReading: "そと", englishGloss: "outside" },
    ],
    grammar: [
      { pattern: "〜前に", englishGloss: "before doing" },
      { pattern: "〜てから", englishGloss: "after doing" },
      { pattern: "〜ながら", englishGloss: "while doing (simultaneously)" },
    ],
  },
  {
    lessonNumber: 27,
    isReview: false,
    theme: "「何を着ますか」",
    objectives: [
      "Talk about clothing and appearance",
      "Ask polite questions with 〜でしょうか",
      "Say something is too much with 〜すぎます",
    ],
    vocab: [
      { japanese: "服", reading: "ふく", englishGloss: "clothes" },
      { japanese: "シャツ", reading: "しゃつ", englishGloss: "shirt" },
      { japanese: "ズボン", reading: "ずぼん", englishGloss: "pants" },
      { japanese: "スカート", reading: "すかーと", englishGloss: "skirt" },
      { japanese: "靴", reading: "くつ", englishGloss: "shoes" },
      { japanese: "帽子", reading: "ぼうし", englishGloss: "hat" },
      { japanese: "かばん", reading: "かばん", englishGloss: "bag" },
      { japanese: "眼鏡", reading: "めがね", englishGloss: "glasses" },
      { japanese: "着る", reading: "きる", englishGloss: "to wear" },
      { japanese: "履く", reading: "はく", englishGloss: "to wear (footwear)" },
      { japanese: "かぶる", reading: "かぶる", englishGloss: "to wear (on the head)" },
      { japanese: "脱ぐ", reading: "ぬぐ", englishGloss: "to take off" },
      { japanese: "手袋", reading: "てぶくろ", englishGloss: "gloves" },
      { japanese: "ネクタイ", reading: "ねくたい", englishGloss: "necktie" },
      { japanese: "コート", reading: "こーと", englishGloss: "coat" },
      { japanese: "セーター", reading: "せーたー", englishGloss: "sweater" },
      { japanese: "かっこいい", reading: "かっこいい", englishGloss: "cool-looking" },
      { japanese: "派手な", reading: "はでな", englishGloss: "flashy" },
      { japanese: "似合う", reading: "にあう", englishGloss: "to suit, look good on" },
      { japanese: "靴下", reading: "くつした", englishGloss: "socks" },
      { japanese: "指輪", reading: "ゆびわ", englishGloss: "ring" },
      { japanese: "ワンピース", reading: "わんぴーす", englishGloss: "dress" },
      { japanese: "下着", reading: "したぎ", englishGloss: "underwear" },
      { japanese: "地味な", reading: "じみな", englishGloss: "plain, simple (style)" },
      { japanese: "サンダル", reading: "さんだる", englishGloss: "sandals" },
    ],
    kanji: [
      { character: "服", onReading: "フク", kunReading: "—", englishGloss: "clothes" },
      { character: "着", onReading: "チャク", kunReading: "き.る", englishGloss: "wear, arrive" },
      { character: "色", onReading: "ショク、シキ", kunReading: "いろ", englishGloss: "color" },
    ],
    grammar: [
      { pattern: "〜たり〜たりします", englishGloss: "doing things such as..." },
      { pattern: "〜あげます", englishGloss: "I give (to someone)" },
      { pattern: "〜もらいます", englishGloss: "I receive (from someone)" },
    ],
  },
  {
    lessonNumber: 28,
    isReview: false,
    theme: "「仕事は何ですか」",
    objectives: [
      "Talk about jobs and the workplace",
      "Explain things with 〜という〜",
      "Talk about doing things in advance with 〜ておきます",
    ],
    vocab: [
      { japanese: "公務員", reading: "こうむいん", englishGloss: "civil servant" },
      { japanese: "警察官", reading: "けいさつかん", englishGloss: "police officer" },
      { japanese: "料理人", reading: "りょうりにん", englishGloss: "chef" },
      { japanese: "エンジニア", reading: "えんじにあ", englishGloss: "engineer" },
      { japanese: "主婦", reading: "しゅふ", englishGloss: "housewife" },
      { japanese: "給料", reading: "きゅうりょう", englishGloss: "salary" },
      { japanese: "出勤する", reading: "しゅっきんする", englishGloss: "to go to work" },
      { japanese: "退勤する", reading: "たいきんする", englishGloss: "to leave work" },
      { japanese: "名刺", reading: "めいし", englishGloss: "business card" },
      { japanese: "紹介する", reading: "しょうかいする", englishGloss: "to introduce" },
      { japanese: "就職する", reading: "しゅうしょくする", englishGloss: "to get employed" },
      { japanese: "辞める", reading: "やめる", englishGloss: "to quit (a job)" },
      { japanese: "昇進する", reading: "しょうしんする", englishGloss: "to be promoted" },
      { japanese: "残業する", reading: "ざんぎょうする", englishGloss: "to work overtime" },
      { japanese: "部長", reading: "ぶちょう", englishGloss: "department manager" },
      { japanese: "同僚", reading: "どうりょう", englishGloss: "coworker" },
      { japanese: "面接", reading: "めんせつ", englishGloss: "job interview" },
      { japanese: "履歴書", reading: "りれきしょ", englishGloss: "resume" },
      { japanese: "契約", reading: "けいやく", englishGloss: "contract" },
      { japanese: "社長", reading: "しゃちょう", englishGloss: "company president" },
      { japanese: "部下", reading: "ぶか", englishGloss: "subordinate" },
      { japanese: "事務所", reading: "じむしょ", englishGloss: "office" },
      { japanese: "出張する", reading: "しゅっちょうする", englishGloss: "to go on a business trip" },
      { japanese: "休暇", reading: "きゅうか", englishGloss: "leave, vacation" },
      { japanese: "定年", reading: "ていねん", englishGloss: "retirement age" },
    ],
    kanji: [
      { character: "仕", onReading: "シ", kunReading: "—", englishGloss: "serve, work" },
      { character: "事", onReading: "ジ", kunReading: "こと", englishGloss: "matter, affair" },
      { character: "働", onReading: "ドウ", kunReading: "はたら.く", englishGloss: "work" },
    ],
    grammar: [
      { pattern: "〜くれます", englishGloss: "someone gives (to me)" },
      { pattern: "〜と思います", englishGloss: "I think that..." },
      { pattern: "〜でしょう", englishGloss: "probably" },
    ],
  },
  {
    lessonNumber: 29,
    isReview: false,
    theme: "「レストランで」",
    objectives: [
      "Order at a restaurant",
      "Talk about past experiences with 〜たことがあります",
      "Make polite prohibitions with 〜ないでください",
    ],
    vocab: [
      { japanese: "食堂", reading: "しょくどう", englishGloss: "cafeteria, dining hall" },
      { japanese: "メニュー", reading: "めにゅー", englishGloss: "menu" },
      { japanese: "注文する", reading: "ちゅうもんする", englishGloss: "to order" },
      { japanese: "席", reading: "せき", englishGloss: "seat" },
      { japanese: "お勘定", reading: "おかんじょう", englishGloss: "the check, bill" },
      { japanese: "領収書", reading: "りょうしゅうしょ", englishGloss: "receipt" },
      { japanese: "いただきます", reading: "いただきます", englishGloss: "phrase said before eating" },
      { japanese: "ごちそうさま", reading: "ごちそうさま", englishGloss: "phrase said after eating" },
      { japanese: "辛い", reading: "からい", englishGloss: "spicy" },
      { japanese: "甘い", reading: "あまい", englishGloss: "sweet" },
      { japanese: "冷たい", reading: "つめたい", englishGloss: "cold (to touch/drink)" },
      { japanese: "熱い", reading: "あつい", englishGloss: "hot (to touch)" },
      { japanese: "飲み物", reading: "のみもの", englishGloss: "drink" },
      { japanese: "食べ物", reading: "たべもの", englishGloss: "food" },
      { japanese: "デザート", reading: "でざーと", englishGloss: "dessert" },
      { japanese: "セット", reading: "せっと", englishGloss: "set meal" },
      { japanese: "カウンター", reading: "かうんたー", englishGloss: "counter" },
      { japanese: "おすすめ", reading: "おすすめ", englishGloss: "recommendation" },
      { japanese: "持ち帰り", reading: "もちかえり", englishGloss: "takeout" },
      { japanese: "定食", reading: "ていしょく", englishGloss: "set meal (Japanese style)" },
      { japanese: "割り勘", reading: "わりかん", englishGloss: "splitting the bill" },
      { japanese: "満席", reading: "まんせき", englishGloss: "fully booked" },
      { japanese: "味", reading: "あじ", englishGloss: "taste" },
      { japanese: "量", reading: "りょう", englishGloss: "quantity, amount" },
      { japanese: "混雑する", reading: "こんざつする", englishGloss: "to be crowded" },
    ],
    kanji: [
      { character: "料", onReading: "リョウ", kunReading: "—", englishGloss: "fee, materials" },
      { character: "理", onReading: "リ", kunReading: "—", englishGloss: "reason, logic" },
      { character: "好", onReading: "コウ", kunReading: "す.き", englishGloss: "like, favorable" },
    ],
    grammar: [
      { pattern: "〜そうです（様態）", englishGloss: "looks like, seems" },
      { pattern: "〜たことがあります", englishGloss: "have done before" },
      { pattern: "〜ないでください", englishGloss: "please don't do" },
    ],
  },
  review(30),
  {
    lessonNumber: 31,
    isReview: false,
    theme: "「道を教えてください」",
    objectives: [
      "Ask for and understand directions",
      "Use the nai-form of verbs",
      "Express obligation and its absence",
    ],
    vocab: [
      { japanese: "曲がる", reading: "まがる", englishGloss: "to turn" },
      { japanese: "まっすぐ", reading: "まっすぐ", englishGloss: "straight ahead" },
      { japanese: "信号", reading: "しんごう", englishGloss: "traffic light" },
      { japanese: "交差点", reading: "こうさてん", englishGloss: "intersection" },
      { japanese: "近く", reading: "ちかく", englishGloss: "nearby" },
      { japanese: "隣", reading: "となり", englishGloss: "next to" },
      { japanese: "間", reading: "あいだ", englishGloss: "between" },
      { japanese: "横", reading: "よこ", englishGloss: "side" },
      { japanese: "そば", reading: "そば", englishGloss: "beside, nearby" },
      { japanese: "向かい", reading: "むかい", englishGloss: "across from" },
      { japanese: "遠く", reading: "とおく", englishGloss: "far away" },
      { japanese: "分かりやすい", reading: "わかりやすい", englishGloss: "easy to understand" },
      { japanese: "分かりにくい", reading: "わかりにくい", englishGloss: "hard to understand" },
      { japanese: "渡る", reading: "わたる", englishGloss: "to cross" },
      { japanese: "通る", reading: "とおる", englishGloss: "to pass through" },
      { japanese: "突き当たり", reading: "つきあたり", englishGloss: "end of the road" },
      { japanese: "角", reading: "かど", englishGloss: "corner" },
      { japanese: "東", reading: "ひがし", englishGloss: "east" },
      { japanese: "西", reading: "にし", englishGloss: "west" },
      { japanese: "南", reading: "みなみ", englishGloss: "south" },
      { japanese: "北", reading: "きた", englishGloss: "north" },
      { japanese: "方向", reading: "ほうこう", englishGloss: "direction" },
      { japanese: "迷う", reading: "まよう", englishGloss: "to get lost" },
      { japanese: "標識", reading: "ひょうしき", englishGloss: "road sign" },
      { japanese: "目印", reading: "めじるし", englishGloss: "landmark" },
    ],
    kanji: [
      { character: "近", onReading: "キン", kunReading: "ちか.い", englishGloss: "near" },
      { character: "遠", onReading: "エン", kunReading: "とお.い", englishGloss: "far" },
      { character: "前", onReading: "ゼン", kunReading: "まえ", englishGloss: "front, before" },
    ],
    grammar: [
      { pattern: "動詞のない形", englishGloss: "nai-form of verbs" },
      { pattern: "〜なければなりません", englishGloss: "must do" },
      { pattern: "〜なくてもいいです", englishGloss: "don't have to do" },
    ],
  },
  {
    lessonNumber: 32,
    isReview: false,
    theme: "「日本語が話せますか」",
    objectives: [
      "Talk about language and other abilities",
      "State future intentions with 〜つもりです",
      "Ask polite questions with 〜でしょうか",
    ],
    vocab: [
      { japanese: "できる", reading: "できる", englishGloss: "to be able to do" },
      { japanese: "話せる", reading: "はなせる", englishGloss: "can speak" },
      { japanese: "読める", reading: "よめる", englishGloss: "can read" },
      { japanese: "書ける", reading: "かける", englishGloss: "can write" },
      { japanese: "聞こえる", reading: "きこえる", englishGloss: "to be audible" },
      { japanese: "見える", reading: "みえる", englishGloss: "to be visible" },
      { japanese: "上手な", reading: "じょうずな", englishGloss: "skillful" },
      { japanese: "下手な", reading: "へたな", englishGloss: "unskillful" },
      { japanese: "練習する", reading: "れんしゅうする", englishGloss: "to practice" },
      { japanese: "教わる", reading: "おそわる", englishGloss: "to be taught" },
      { japanese: "続ける", reading: "つづける", englishGloss: "to continue" },
      { japanese: "止める", reading: "やめる", englishGloss: "to stop, quit (general)" },
      { japanese: "始める", reading: "はじめる", englishGloss: "to start (something)" },
      { japanese: "能力", reading: "のうりょく", englishGloss: "ability" },
      { japanese: "才能", reading: "さいのう", englishGloss: "talent" },
      { japanese: "可能", reading: "かのう", englishGloss: "possible" },
      { japanese: "不可能", reading: "ふかのう", englishGloss: "impossible" },
      { japanese: "マスターする", reading: "ますたーする", englishGloss: "to master" },
      { japanese: "身につける", reading: "みにつける", englishGloss: "to acquire (a skill)" },
      { japanese: "挑戦する", reading: "ちょうせんする", englishGloss: "to challenge oneself" },
      { japanese: "成長する", reading: "せいちょうする", englishGloss: "to grow" },
      { japanese: "達成する", reading: "たっせいする", englishGloss: "to achieve" },
      { japanese: "諦める", reading: "あきらめる", englishGloss: "to give up" },
      { japanese: "努力する", reading: "どりょくする", englishGloss: "to make an effort" },
      { japanese: "集中する", reading: "しゅうちゅうする", englishGloss: "to concentrate" },
    ],
    kanji: [
      { character: "上", onReading: "ジョウ", kunReading: "うえ、あ.げる", englishGloss: "up, above" },
      { character: "手", onReading: "シュ", kunReading: "て", englishGloss: "hand" },
      { character: "下", onReading: "カ、ゲ", kunReading: "した、さ.げる", englishGloss: "down, below" },
    ],
    grammar: [
      { pattern: "〜つもりです", englishGloss: "intend to" },
      { pattern: "〜でしょうか（丁寧な質問）", englishGloss: "polite question (softer)" },
      { pattern: "〜すぎます", englishGloss: "too much" },
    ],
  },
  {
    lessonNumber: 33,
    isReview: false,
    theme: "「どちらが好きですか」",
    objectives: [
      "Compare two or more things",
      "Use the ば-conditional",
      "Talk about relative size, weight, and strength",
    ],
    vocab: [
      { japanese: "もっと", reading: "もっと", englishGloss: "more" },
      { japanese: "一番", reading: "いちばん", englishGloss: "the most" },
      { japanese: "より", reading: "より", englishGloss: "than" },
      { japanese: "ほう", reading: "ほう", englishGloss: "the one (in a comparison)" },
      { japanese: "違う", reading: "ちがう", englishGloss: "different, wrong" },
      { japanese: "比べる", reading: "くらべる", englishGloss: "to compare" },
      { japanese: "どちらが", reading: "どちらが", englishGloss: "which (polite)" },
      { japanese: "どっち", reading: "どっち", englishGloss: "which (casual)" },
      { japanese: "長い", reading: "ながい", englishGloss: "long" },
      { japanese: "短い", reading: "みじかい", englishGloss: "short" },
      { japanese: "重い", reading: "おもい", englishGloss: "heavy" },
      { japanese: "軽い", reading: "かるい", englishGloss: "light (weight)" },
      { japanese: "強い", reading: "つよい", englishGloss: "strong" },
      { japanese: "弱い", reading: "よわい", englishGloss: "weak" },
      { japanese: "差", reading: "さ", englishGloss: "difference, gap" },
      { japanese: "以上", reading: "いじょう", englishGloss: "or more" },
      { japanese: "以下", reading: "いか", englishGloss: "or less" },
      { japanese: "同じくらい", reading: "おなじくらい", englishGloss: "about the same" },
      { japanese: "まし", reading: "まし", englishGloss: "better (of two bad options)" },
      { japanese: "かなり", reading: "かなり", englishGloss: "quite, considerably" },
      { japanese: "少し", reading: "すこし", englishGloss: "a little" },
      { japanese: "たくさん", reading: "たくさん", englishGloss: "a lot" },
      { japanese: "全然", reading: "ぜんぜん", englishGloss: "not at all" },
      { japanese: "意外と", reading: "いがいと", englishGloss: "surprisingly" },
      { japanese: "特に", reading: "とくに", englishGloss: "especially" },
    ],
    kanji: [
      { character: "長", onReading: "チョウ", kunReading: "なが.い", englishGloss: "long" },
      { character: "短", onReading: "タン", kunReading: "みじか.い", englishGloss: "short" },
      { character: "強", onReading: "キョウ", kunReading: "つよ.い", englishGloss: "strong" },
    ],
    grammar: [
      { pattern: "〜という〜", englishGloss: "called, named..." },
      { pattern: "〜ておきます", englishGloss: "to do in advance" },
      { pattern: "動詞のば形（条件）", englishGloss: "ba-conditional" },
    ],
  },
  {
    lessonNumber: 34,
    isReview: false,
    theme: "「〜てもいいですか」",
    objectives: [
      "Talk about rules and permission",
      "Use たら-conditional and なら-conditional",
      "Talk about things becoming a certain way",
    ],
    vocab: [
      { japanese: "許可", reading: "きょか", englishGloss: "permission" },
      { japanese: "禁止", reading: "きんし", englishGloss: "prohibition" },
      { japanese: "規則", reading: "きそく", englishGloss: "rule" },
      { japanese: "ルール", reading: "るーる", englishGloss: "rule" },
      { japanese: "守る", reading: "まもる", englishGloss: "to keep, protect (rules)" },
      { japanese: "注意する", reading: "ちゅういする", englishGloss: "to be careful, warn" },
      { japanese: "危ない", reading: "あぶない", englishGloss: "dangerous" },
      { japanese: "安全な", reading: "あんぜんな", englishGloss: "safe" },
      { japanese: "自由な", reading: "じゆうな", englishGloss: "free" },
      { japanese: "決まり", reading: "きまり", englishGloss: "rule, custom" },
      { japanese: "条件", reading: "じょうけん", englishGloss: "condition" },
      { japanese: "義務", reading: "ぎむ", englishGloss: "obligation" },
      { japanese: "禁煙", reading: "きんえん", englishGloss: "no smoking" },
      { japanese: "立入禁止", reading: "たちいりきんし", englishGloss: "no entry" },
      { japanese: "必ず", reading: "かならず", englishGloss: "certainly, without fail" },
      { japanese: "絶対に", reading: "ぜったいに", englishGloss: "absolutely" },
      { japanese: "勝手に", reading: "かってに", englishGloss: "without permission" },
      { japanese: "自分で", reading: "じぶんで", englishGloss: "by oneself" },
      { japanese: "責任", reading: "せきにん", englishGloss: "responsibility" },
      { japanese: "使用する", reading: "しようする", englishGloss: "to use (formal)" },
      { japanese: "禁止する", reading: "きんしする", englishGloss: "to prohibit" },
      { japanese: "従う", reading: "したがう", englishGloss: "to follow (rules)" },
      { japanese: "違反する", reading: "いはんする", englishGloss: "to violate" },
      { japanese: "認める", reading: "みとめる", englishGloss: "to approve, admit" },
      { japanese: "制限する", reading: "せいげんする", englishGloss: "to restrict" },
    ],
    kanji: [
      { character: "使", onReading: "シ", kunReading: "つか.う", englishGloss: "use" },
      { character: "守", onReading: "シュ", kunReading: "まも.る", englishGloss: "protect, keep" },
      { character: "自", onReading: "ジ、シ", kunReading: "みずか.ら", englishGloss: "self" },
    ],
    grammar: [
      { pattern: "〜てしまいます", englishGloss: "completion, unfortunate result" },
      { pattern: "〜ようになります", englishGloss: "to come to be able to / to start" },
      { pattern: "〜ことができます", englishGloss: "can do, ability" },
    ],
  },
  review(35),
  {
    lessonNumber: 36,
    isReview: false,
    theme: "「〜たことがあります」",
    objectives: [
      "Talk about past experiences and how things have changed",
      "Use the passive form",
      "Use the causative form",
    ],
    vocab: [
      { japanese: "前に", reading: "まえに", englishGloss: "before" },
      { japanese: "一度", reading: "いちど", englishGloss: "once" },
      { japanese: "二度", reading: "にど", englishGloss: "twice" },
      { japanese: "初めて", reading: "はじめて", englishGloss: "for the first time" },
      { japanese: "経験", reading: "けいけん", englishGloss: "experience" },
      { japanese: "思い出", reading: "おもいで", englishGloss: "memory" },
      { japanese: "子供の時", reading: "こどものとき", englishGloss: "when (I was) a child" },
      { japanese: "昔", reading: "むかし", englishGloss: "long ago" },
      { japanese: "当時", reading: "とうじ", englishGloss: "at that time" },
      { japanese: "以前", reading: "いぜん", englishGloss: "formerly" },
      { japanese: "もう", reading: "もう", englishGloss: "already" },
      { japanese: "まだ", reading: "まだ", englishGloss: "still, not yet" },
      { japanese: "すでに", reading: "すでに", englishGloss: "already (formal)" },
      { japanese: "やっと", reading: "やっと", englishGloss: "finally" },
      { japanese: "ついに", reading: "ついに", englishGloss: "at last" },
      { japanese: "結局", reading: "けっきょく", englishGloss: "in the end" },
      { japanese: "実は", reading: "じつは", englishGloss: "actually" },
      { japanese: "実際に", reading: "じっさいに", englishGloss: "in reality" },
      { japanese: "変わる", reading: "かわる", englishGloss: "to change" },
      { japanese: "育つ", reading: "そだつ", englishGloss: "to grow up" },
      { japanese: "過ごす", reading: "すごす", englishGloss: "to spend (time)" },
      { japanese: "懐かしい", reading: "なつかしい", englishGloss: "nostalgic" },
      { japanese: "記憶", reading: "きおく", englishGloss: "memory (recollection)" },
      { japanese: "体験する", reading: "たいけんする", englishGloss: "to experience" },
      { japanese: "振り返る", reading: "ふりかえる", englishGloss: "to look back" },
    ],
    kanji: [
      { character: "度", onReading: "ド", kunReading: "—", englishGloss: "times, degree" },
      { character: "昔", onReading: "セキ", kunReading: "むかし", englishGloss: "long ago" },
      { character: "実", onReading: "ジツ", kunReading: "み", englishGloss: "truth, fruit" },
    ],
    grammar: [
      { pattern: "〜たほうがいいです", englishGloss: "had better do" },
      { pattern: "〜ないほうがいいです", englishGloss: "had better not do" },
      { pattern: "〜かもしれません", englishGloss: "might be" },
    ],
  },
  {
    lessonNumber: 37,
    isReview: false,
    theme: "「将来の夢」",
    objectives: [
      "Talk about future plans and dreams",
      "Express what you want someone to do with 〜てほしいです",
      "Use conditionals to talk about outcomes",
    ],
    vocab: [
      { japanese: "つもり", reading: "つもり", englishGloss: "intention" },
      { japanese: "計画", reading: "けいかく", englishGloss: "plan" },
      { japanese: "今度", reading: "こんど", englishGloss: "next time" },
      { japanese: "将来", reading: "しょうらい", englishGloss: "the future" },
      { japanese: "夢", reading: "ゆめ", englishGloss: "dream" },
      { japanese: "目標", reading: "もくひょう", englishGloss: "goal" },
      { japanese: "決まる", reading: "きまる", englishGloss: "to be decided" },
      { japanese: "考える", reading: "かんがえる", englishGloss: "to think, consider" },
      { japanese: "準備する", reading: "じゅんびする", englishGloss: "to prepare" },
      { japanese: "楽しみ", reading: "たのしみ", englishGloss: "looking forward to" },
      { japanese: "期待する", reading: "きたいする", englishGloss: "to expect, look forward to" },
      { japanese: "希望する", reading: "きぼうする", englishGloss: "to hope" },
      { japanese: "目的", reading: "もくてき", englishGloss: "purpose" },
      { japanese: "チャンス", reading: "ちゃんす", englishGloss: "chance" },
      { japanese: "チャレンジする", reading: "ちゃれんじする", englishGloss: "to try, take on a challenge" },
      { japanese: "実現する", reading: "じつげんする", englishGloss: "to realize, come true" },
      { japanese: "叶う", reading: "かなう", englishGloss: "to come true (a wish)" },
      { japanese: "変える", reading: "かえる", englishGloss: "to change (something)" },
      { japanese: "決断する", reading: "けつだんする", englishGloss: "to make a decision" },
      { japanese: "悩む", reading: "なやむ", englishGloss: "to worry, agonize" },
      { japanese: "相談する", reading: "そうだんする", englishGloss: "to consult" },
      { japanese: "アドバイス", reading: "あどばいす", englishGloss: "advice" },
      { japanese: "提案する", reading: "ていあんする", englishGloss: "to propose" },
      { japanese: "見通し", reading: "みとおし", englishGloss: "outlook, prospect" },
      { japanese: "意欲", reading: "いよく", englishGloss: "motivation" },
    ],
    kanji: [
      { character: "予", onReading: "ヨ", kunReading: "—", englishGloss: "in advance" },
      { character: "定", onReading: "テイ", kunReading: "さだ.める", englishGloss: "decide, fix" },
      { character: "考", onReading: "コウ", kunReading: "かんが.える", englishGloss: "think, consider" },
    ],
    grammar: [
      { pattern: "〜そうです（伝聞）", englishGloss: "I heard that..." },
      { pattern: "〜と、〜（自動的な結果）", englishGloss: "whenever X, Y happens" },
      { pattern: "〜たら、〜", englishGloss: "if/when... (tara-conditional)" },
    ],
  },
  {
    lessonNumber: 38,
    isReview: false,
    theme: "「市役所で」",
    objectives: [
      "Handle errands at the post office and city hall",
      "Fill out forms and ask about procedures",
      "Review requests, permission, and obligation grammar",
    ],
    vocab: [
      { japanese: "手続きする", reading: "てつづきする", englishGloss: "to process, do procedures" },
      { japanese: "申し込む", reading: "もうしこむ", englishGloss: "to apply" },
      { japanese: "書類", reading: "しょるい", englishGloss: "document" },
      { japanese: "サイン", reading: "さいん", englishGloss: "signature" },
      { japanese: "印鑑", reading: "いんかん", englishGloss: "personal seal" },
      { japanese: "役所", reading: "やくしょ", englishGloss: "government office" },
      { japanese: "市役所", reading: "しやくしょ", englishGloss: "city hall" },
      { japanese: "窓口", reading: "まどぐち", englishGloss: "counter, window" },
      { japanese: "記入する", reading: "きにゅうする", englishGloss: "to fill in" },
      { japanese: "コピーする", reading: "こぴーする", englishGloss: "to photocopy" },
      { japanese: "ファックス", reading: "ふぁっくす", englishGloss: "fax" },
      { japanese: "切手", reading: "きって", englishGloss: "stamp" },
      { japanese: "封筒", reading: "ふうとう", englishGloss: "envelope" },
      { japanese: "小包", reading: "こづつみ", englishGloss: "parcel" },
      { japanese: "送料", reading: "そうりょう", englishGloss: "shipping fee" },
      { japanese: "振込", reading: "ふりこみ", englishGloss: "bank transfer" },
      { japanese: "口座", reading: "こうざ", englishGloss: "bank account" },
      { japanese: "暗証番号", reading: "あんしょうばんごう", englishGloss: "PIN number" },
      { japanese: "引き出す", reading: "ひきだす", englishGloss: "to withdraw (money)" },
      { japanese: "預ける", reading: "あずける", englishGloss: "to deposit" },
      { japanese: "手数料", reading: "てすうりょう", englishGloss: "fee, commission" },
      { japanese: "保険証", reading: "ほけんしょう", englishGloss: "insurance card" },
      { japanese: "身分証明書", reading: "みぶんしょうめいしょ", englishGloss: "ID card" },
      { japanese: "期限", reading: "きげん", englishGloss: "deadline" },
      { japanese: "遅れる", reading: "おくれる", englishGloss: "to be late, delayed" },
    ],
    kanji: [
      { character: "局", onReading: "キョク", kunReading: "—", englishGloss: "office, bureau" },
      { character: "証", onReading: "ショウ", kunReading: "—", englishGloss: "proof, certificate" },
      { character: "費", onReading: "ヒ", kunReading: "—", englishGloss: "expense, cost" },
    ],
    grammar: [
      { pattern: "〜なら、〜", englishGloss: "if it's the case that..." },
      { pattern: "〜くなります／〜になります", englishGloss: "to become..." },
      { pattern: "受身形（〜られます）", englishGloss: "passive form" },
    ],
  },
  {
    lessonNumber: 39,
    isReview: false,
    theme: "「お世話になりました」",
    objectives: [
      "Use common farewell and gratitude set phrases",
      "Wrap up N5 vocabulary and grammar",
      "Use the causative form and 〜てほしいです",
    ],
    vocab: [
      { japanese: "すみません", reading: "すみません", englishGloss: "excuse me, sorry" },
      { japanese: "ごめんなさい", reading: "ごめんなさい", englishGloss: "I'm sorry" },
      { japanese: "ありがとう", reading: "ありがとう", englishGloss: "thank you" },
      { japanese: "どういたしまして", reading: "どういたしまして", englishGloss: "you're welcome" },
      { japanese: "お願いします", reading: "おねがいします", englishGloss: "please (set phrase)" },
      { japanese: "失礼します", reading: "しつれいします", englishGloss: "excuse me (entering/leaving)" },
      { japanese: "お大事に", reading: "おだいじに", englishGloss: "take care (to someone sick)" },
      { japanese: "お疲れ様", reading: "おつかれさま", englishGloss: "thank you for your hard work" },
      { japanese: "頑張って", reading: "がんばって", englishGloss: "do your best!" },
      { japanese: "おめでとう", reading: "おめでとう", englishGloss: "congratulations" },
      { japanese: "いってきます", reading: "いってきます", englishGloss: "I'm off (leaving home)" },
      { japanese: "いってらっしゃい", reading: "いってらっしゃい", englishGloss: "see you off (response)" },
      { japanese: "ただいま", reading: "ただいま", englishGloss: "I'm home" },
      { japanese: "おかえりなさい", reading: "おかえりなさい", englishGloss: "welcome home" },
      { japanese: "お邪魔します", reading: "おじゃまします", englishGloss: "excuse me for intruding" },
      { japanese: "気をつけて", reading: "きをつけて", englishGloss: "take care, be careful" },
      { japanese: "お先に失礼します", reading: "おさきにしつれいします", englishGloss: "excuse me for leaving first" },
      { japanese: "よくできました", reading: "よくできました", englishGloss: "well done" },
      { japanese: "お陰様で", reading: "おかげさまで", englishGloss: "thanks to you, I'm doing well" },
      { japanese: "お世話になります", reading: "おせわになります", englishGloss: "thank you for your support (formal opening)" },
      { japanese: "ようこそ", reading: "ようこそ", englishGloss: "welcome" },
      { japanese: "お邪魔しました", reading: "おじゃましました", englishGloss: "sorry for having intruded (on leaving)" },
      { japanese: "お元気で", reading: "おげんきで", englishGloss: "take care, stay well" },
      { japanese: "失礼しました", reading: "しつれいしました", englishGloss: "I'm sorry for my rudeness (past)" },
      { japanese: "どうぞよろしく", reading: "どうぞよろしく", englishGloss: "nice to meet you (response)" },
    ],
    kanji: [
      { character: "失", onReading: "シツ", kunReading: "うしな.う", englishGloss: "lose, fail" },
      { character: "礼", onReading: "レイ", kunReading: "—", englishGloss: "courtesy, thanks" },
      { character: "元", onReading: "ゲン、ガン", kunReading: "もと", englishGloss: "origin, base" },
    ],
    grammar: [
      { pattern: "使役形（〜させます）", englishGloss: "causative form" },
      { pattern: "〜てもらいたいです／〜てほしいです", englishGloss: "want someone to do" },
      { pattern: "〜させてください", englishGloss: "please let me do" },
    ],
  },
  review(40),
];
